spring:
  application:
    name: rabbit
  data:
    mongodb:
      uri: ${MONGODB_URI}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
            redirect-uri: ${CLIENT_BASE_URL}/api/auth/callback
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


jwt:
  accessTokenKey: ${JWT_ACCESS_TOKEN_KEY}
  refreshTokenKey: ${JWT_REFRESH_TOKEN_KEY}
  accessTokenExpires: 1800000
  refreshTokenExpires: 259200000
